[WD-10977] chore: Allow Contextual Menu Component to be positionalled optimally,…
canonical/react-components pull request #1101
Opened 2024-06-27 17:28 UTC by Kxiru

… vertically

## Done

- Added a scss file for Contextual Menu
- Implemented logic by @mas-who to vertically position the Menu optimally based on the viewport height.

## QA

### Storybook

To see rendered examples of all react-components, run:

```shell
yarn start
```

### QA in your project

from `react-components` run:

```shell
yarn build
npm pack
```

Install the resulting tarball in your project with:

```shell
yarn add <path-to-tarball>
```

### Percy steps

N/A

## Fixes
- Contextual Menu dropdown now displays "upwards" if there is not enough space downwards.

![image](https://github.com/canonical/react-components/assets/58699506/2ab95787-38d3-46d3-9d82-e203f833fc85)

2024-06-27 17:28 UTC, webteam-app commented
### [<img src='https://assets.ubuntu.com/v1/6baef514-ubuntu-circle-of-friends-large.svg' height=32 width=32> Demo</img>](https://react-components-1101.demos.haus)
### [<img src='https://assets.ubuntu.com/v1/e512b0e2-jenkins.svg' height=32 width=32> Jenkins </img>](https://jenkins.canonical.com/webteam/job/start-demo/2466)
### [<img src='https://assets.ubuntu.com/v1/7144ec6d-logo-jaas-icon.svg' height=32 width=32> demos.haus </img>](https://demos.haus)

2024-06-27 23:35 UTC, huwshimi reviewed
It looks like this is already intended to be supported using the `autoAdjust` prop, however it currently takes into account the scroll area, not the window space.

If there's room in the scroll area below:

<img width="688" alt="Screenshot 2024-06-28 at 9 28 14 AM" src="https://github.com/canonical/react-components/assets/361637/6e010adf-c687-4222-a5f6-616bec079592">

If there's no room below:

<img width="667" alt="Screenshot 2024-06-28 at 9 28 34 AM" src="https://github.com/canonical/react-components/assets/361637/578040d0-a669-450e-a4be-4e363d04705b">

It looks like this could be fixed where the vertical space is calculated:

https://github.com/canonical/react-components/blob/f704e2ed5742fff7b648b9d02f64fe4d7630ad18/src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx#L228

2024-06-28 12:24 UTC, Kxiru commented
Thanks @huwshimi for your review. Are you saying that the implemented logic would be better placed / integrated into updateVerticalPosition?

2024-06-30 23:43 UTC, huwshimi commented
> Thanks @huwshimi for your review. Are you saying that the implemented logic would be better placed / integrated into updateVerticalPosition?

Yes please!

2024-07-09 00:11 UTC, huwshimi requested changes
This component already has support for adjusting the dropdown to be above or below, so there's no need to add additional state. Instead, you can just change the calculation from being relative to the scroll parent, to being relative to the window here:

https://github.com/canonical/react-components/blob/9668ce671a76d74cb3d7f1153011ad2d7c73062d/src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx#L239

2024-07-09 12:16 UTC, Kxiru commented
> This component already has support for adjusting the dropdown to be above or below, so there's no need to add additional state. Instead, you can just change the calculation from being relative to the scroll parent, to being relative to the window here:
> 
> https://github.com/canonical/react-components/blob/9668ce671a76d74cb3d7f1153011ad2d7c73062d/src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx#L239

Don't we want the component to be able to react according to BOTH the scroll parent and the window as well?

2024-07-09 23:48 UTC, huwshimi commented
> Don't we want the component to be able to react according to BOTH the scroll parent and the window as well?

Are you thinking of a scenario where the menu is at the bottom of a scrolling container, but that container is not at the bottom of the screen, so you want the menu to flip to above the button?

If that's the behaviour you want then you could add a second rect that is relative to the window and then adjust this calculation:

https://github.com/canonical/react-components/blob/main/src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx#L250-L252

This would use both rects to calculate "dropdown fits below in scroll parent" AND "dropdown fits below in window", in pseudo code this could be something like:

```typescript
    setVerticalPosition(
      scrollParentSpaceBelow >= dropdownHeight  && windowSpaceBelow >= dropdownHeight || windowSpaceBelow > spaceAbove ? "bottom" : "top"
    );
```

2024-07-12 15:54 UTC, Kxiru commented
@huwshimi Hi there!
I have actioned your suggestions. Please let me know if this is in line with what you were thinking :).

2024-07-12 15:55 UTC, edlerd commented on src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx
> +// import "./ContextualMenuDropdown.scss";
```suggestion
```

2024-07-15 00:04 UTC, huwshimi reviewed
This is on the right track now, thanks for persisting. Right now the relation to the window isn't correct so the menu is appearing at the top when there's space below:

<img width="669" alt="Screenshot 2024-07-15 at 9 38 21 AM" src="https://github.com/user-attachments/assets/67d41380-ca3a-44c9-9d84-4029246a06b2">

This PR could also use some tests, they might help during implementation to track down the issues I've mentioned.

2024-07-16 16:03 UTC, Kxiru commented on src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx
>      const dropdownHeight = relativeRect.height;
Thank you for your suggestions. Please review :).

2024-07-19 08:59 UTC, Kxiru commented
@huwshimi , thanks for our chat today! I've pushed the changes that we made and the written suggestions you provided. I'll let you know of my progress with creating a test.

2024-07-24 18:12 UTC, mas-who commented
@huwshimi @Kxiru regarding creating a test for this component, I believe since react testing library uses jsdom, it will be tricky to setup a test that relies on the component render cycle and perform assertion on the final element positions. See this [issue](https://github.com/testing-library/react-testing-library/issues/353#issuecomment-545231016) for example which has a suggestion of directly modifying dom node's prototype to mock the values but I don't think it would work for assertions if we want to check dom element position. I think maybe we can setup the test by moving `updateVerticalPosition` outside of the component and create a unit test for the function?

2024-07-24 18:52 UTC, edlerd commented
> @huwshimi @Kxiru regarding creating a test for this component, I believe since react testing library uses jsdom, it will be tricky to setup a test that relies on the component render cycle and perform assertion on the final element positions. See this [issue](https://github.com/testing-library/react-testing-library/issues/353#issuecomment-545231016) for example which has a suggestion to directly modify a dom node's prototype to mock the values but I don't think it would work for assertions if we want to check dom element position. I think maybe we can setup the test by moving `updateVerticalPosition` outside of the component and create a unit test for the function?

If I understand your problem correctly @mas-who @Kxiru you can have a look at the `updates the tooltip to fit on the screen` test in `Tooltip.test.jsx` for a solution of a very similar problem.

2024-07-24 19:18 UTC, mas-who commented
> > @huwshimi @Kxiru regarding creating a test for this component, I believe since react testing library uses jsdom, it will be tricky to setup a test that relies on the component render cycle and perform assertion on the final element positions. See this [issue](https://github.com/testing-library/react-testing-library/issues/353#issuecomment-545231016) for example which has a suggestion to directly modify a dom node's prototype to mock the values but I don't think it would work for assertions if we want to check dom element position. I think maybe we can setup the test by moving `updateVerticalPosition` outside of the component and create a unit test for the function?
> 
> If I understand your problem correctly @mas-who @Kxiru you can have a look at the `updates the tooltip to fit on the screen` test in `Tooltip.test.jsx` for a solution of a very similar problem.

Hmm not sure if it's the same problem, the calculation performed for positioning the dropdown isn't really based on event listeners. As far as I can tell, what we can assert for this component test case is that it's `top` and `bottom` attributes have been correctly calculated. Note this is due to inline style being [applied](https://github.com/Kxiru/react-components/blob/a135e875be8ec29d05723d20ce62f911c0d3afa9/src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx#L311). To do that, we need to get the dropdown element from the dom after rendering the component, which would have zero dimensions as discussed in the reference issue. This would cause assertion to fail.

2024-07-24 23:44 UTC, huwshimi commented
To get this to work you'll need to mock the functions that don't have dimensions, like we do in this test: https://github.com/canonical/react-components/blob/2825eb98ed253825ef69e63c261c7c9605b15f4f/src/hooks/useWindowFitment.test.ts#L72-L78.

You'll need to do this for the scroll parent, the position node and the dropdown elements.

You'll also need to double render the component as RTL doesn't do full lifecycle rendering so we have to manually rerender the component to make the hooks run after the elements exist in the DOM:

https://github.com/canonical/react-components/blob/2825eb98ed253825ef69e63c261c7c9605b15f4f/src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.test.tsx#L42-L44.

If that doesn't make sense let me know and I can give you a concrete example of how to construct the test.

2024-07-25 15:00 UTC, Kxiru commented
@huwshimi , @mas-who has pushed a commit that  recreates the test environment to check whether VerticalPosition resolves to top or bottom - and consequently, whether the styling attribute of the component Span has a bottom of 0, or not. Please could you let us know your thoughts of the test implementation?

2024-07-25 15:04 UTC, Kxiru commented on src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.tsx
> -    const windowRect = {
For context, this has been removed as the only attribute that is later referenced, is windowRect.height, i.e; window.innerHeight - as replaced/referenced in line 252.

2024-07-25 23:55 UTC, huwshimi commented
> @huwshimi , @mas-who has pushed a commit that recreates the test environment to check whether VerticalPosition resolves to top or bottom - and consequently, whether the styling attribute of the component Span has a bottom of 0, or not. Please could you let us know your thoughts of the test implementation?

This looks good! I think there are two other cases that need tests:
- that the menu is above if there is enough area in the window, but not in the scroll parent
- that the menu is below if there is not enough area in the window or scroll parent, but also that there is more space below than above.

I also think it could be worth splitting the current test into the two assertions to make it clear which mocks are required to make each test pass. It might be helpful to move some of the set up into a function to make the four tests cleaner.

2024-07-26 11:44 UTC, mas-who commented
> > @huwshimi , @mas-who has pushed a commit that recreates the test environment to check whether VerticalPosition resolves to top or bottom - and consequently, whether the styling attribute of the component Span has a bottom of 0, or not. Please could you let us know your thoughts of the test implementation?
> 
> This looks good! I think there are two other cases that need tests:
> 
> * that the menu is above if there is enough area in the window, but not in the scroll parent
> * that the menu is below if there is not enough area in the window or scroll parent, but also that there is more space below than above.
> 
> I also think it could be worth splitting the current test into the two assertions to make it clear which mocks are required to make each test pass. It might be helpful to move some of the set up into a function to make the four tests cleaner.

@huwshimi I've made those changes as mentioned :+1:

2024-07-29 02:19 UTC, huwshimi approved these changes
Thanks for this @Kxiru and @mas-who this looks like it's working well now!

2024-07-29 02:19 UTC, huwshimi commented on src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.test.tsx
> +      // need to mock overflow propertty for scrollparent
```suggestion
      // need to mock overflow property for scrollparent
```

2024-07-29 07:35 UTC, mas-who commented on src/components/ContextualMenu/ContextualMenuDropdown/ContextualMenuDropdown.test.tsx
> +      // need to mock overflow propertty for scrollparent
Thanks for the review @huwshimi !

2024-08-19 15:14 UTC, edlerd approved these changes
LGTM

2024-08-19 15:48 UTC, merged