fix: change title in ApplicationLayout
canonical/react-components pull request #1111
Opened 2024-08-09 12:13 UTC by vladimir-cucu

## Done

- Include the option to change the document title once the `ApplicationLayout` renders. This allow for a consistent behavior with other components like `LoginPageLayout` and will fix bugs like the one bellow.

## Fixes

Fixes: https://github.com/canonical/identity-platform-admin-ui/issues/373
https://warthogs.atlassian.net/browse/WD-14064

2024-08-09 19:57 UTC, bartaz approved these changes
Code looks good to me. I don't have a lot of context on how this would be used, but seems to do what intended.

2024-08-11 23:11 UTC, huwshimi commented
I wonder if this might not be the right approach. I'm not sure the layout components should be managing the window title as I can imagine different apps would want to manage the title through different implementations e.g. through the use of hooks.

Maybe the fix would be to not set the document title in `LoginPageLayout` and allow each application to manage the window title themselves. This would be a breaking change, but worth it I think.

I also noticed that the LoginPageLayout adds an `is-paper` body class but doesn't clean it up when unmounted so there's a couple of unintended side effects by using this component.

2024-08-11 23:12 UTC, huwshimi requested changes
I wonder if this might not be the right approach. I'm not sure the layout components should be managing the window title as I can imagine different apps would want to manage the title through different implementations e.g. through the use of hooks.

Maybe the fix would be to not set the document title in `LoginPageLayout` and allow each application to manage the window title themselves. This would be a breaking change, but worth it I think.

I also noticed that the LoginPageLayout adds an `is-paper` body class but doesn't clean it up when unmounted so there's a couple of unintended side effects by using this component.

2024-08-13 23:39 UTC, huwshimi approved these changes
Thanks for updating this. I think it would be worth noting that this is a breaking change in the release: https://github.com/semantic-release/semantic-release?tab=readme-ov-file#commit-message-format.

2024-08-15 06:43 UTC, merged